-- Run using tasks

-- Run a job on a schedule
CREATE TASK TASK_RUN_JOB_PROCESS_DIMS 
SCHEDULE = 'USING CRON 0 8-17 * * 1-5 America/Los_Angeles'
WAREHOUSE = COMPUTE_WH 
AS CALL RUN_JOB_SEND_EMAIL(5, 3, '<email address>');

-- Run a job when data change based on a STREAM
CREATE TASK TASK_RUN_JOB_PROCESS_DIMS 
SCHEDULE = '1 minute'	
WHEN SYSTEM$STREAM_HAS_DATA('DEV_STG.STR_ORDERS') 
WAREHOUSE = COMPUTE_WH 
AS CALL COALESCE_API_RUN_JOB_COMPLETE(5 , 3);

-- Run a secondary job on completion of a prior job
CREATE TASK TASK_RUN_JOB_PROCESS_FACTS 
AFTER TASK_RUN_JOB_PROCESS_DIMS
AS CALL COALESCE_API_RUN_JOB_COMPLETE(5 , 3);

ALTER TASK TASK_RUN_JOB_PROCESS_DIMS RESUME;
ALTER TASK TASK_RUN_JOB_PROCESS_FACTS RESUME;
